### ISSUE TITLE
Ranch_listener crashes from time to time

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#1004]
the error shown below
recently began to show up on a production websocket server (the listener is exposed to the internet)
what could it possibly be?

=ERROR REPORT==== 11-Jul-2016::11:19:25 ===
Ranch listener online37_listener had connection process started with cowboy_protocol:start_link/4 at <0.3380.0> exit with reason: 
{function_clause,[{lists,zip,
                         [[transport,connection,pid,method,version,peer,host,
                           host_info,port,path,path_info,qs,qs_vals,bindings,
                           headers,p_headers,cookies,meta,body_state,buffer,
                           multipart,resp_compress,resp_state,resp_headers,
                           resp_body,onresponse],
                          []],
                         [{file,"lists.erl"},{line,386}]},
                  {lists,zip,2,[{file,"lists.erl"},{line,386}]},
                  {cowboy_handler,handler_terminate,4,
                                  [{file,"src/cowboy_handler.erl"},
                                   {line,291}]},
                  {cowboy_handler,handler_handle,4,
                                  [{file,"src/cowboy_handler.erl"},
                                   {line,118}]},
                  {cowboy_protocol,execute,4,
                                   [{file,"src/cowboy_protocol.erl"},
                                    {line,442}]}]}

**Comment by essen** [comment]
What version of Cowboy is it?

**Comment by eugene-panferov** [comment]
how to learn which version is it?

**Comment by essen** [comment]
On a running node application:get_key(cowboy, vsn)

**Comment by eugene-panferov** [comment]
1.0.1

**Comment by essen** [comment]
Right I remember. This happens when the handler crashes by returning the wrong thing (ie a different variable than Req when it expects Req) and Cowboy tries to format Req in the error message.

Usually Dialyzer can detect these issues. Otherwise check the return values of every clause of your handler, there's probably somewhere where you call a cowboy_req function and don't match the right thing. Also make sure to follow the 1.0 documentation (and not master/HEAD).

Tell me how it goes, cheers;
