### ISSUE TITLE
cowboy leaks RAM when handler crashes

### ISSUE THREAD

**Issue by brigadier** [ninenines/cowboy#1029]
It looks like cowboy leaks a lot of RAM and maybe other resources when a handler crashes. Could be a DoS vector, as on localhost RAM gets exhausted in seconds with `./wrk -t12 -c1500 -d60s  http://localhost:8080/?q=%u` on `echo_get` example.

v 2.0.0-pre4, can't test with the newer version because having very bad internet there.
Same problem with 1.1.x

the `wrk` does not close connection when makes requests, this might be another reason for eating the RAM when handler throws an exception.

**Comment by essen** [comment]
I will have to try but I'm not quite sure how it could leak anything in the first Cowboy version since nothing is kept around. It's probably just a case of GC being too slow, and should be easily fixed by configuring the maximum number of requests you can do on one connection (defaults to 100).

In Cowboy 2 it's possible that such issues still remain at this time as little has been done to properly test streams handling. But otherwise the same configuration still exists.

**Comment by brigadier** [comment]
No such problems when handler does not crash though.

-----Исходное сообщение-----
От: "Loïc Hoguin" <notifications@github.com>
Отправлено: ‎22.‎09.‎2016 20:53
Кому: "ninenines/cowboy" <cowboy@noreply.github.com>
Копия: "Evgeny M." <eugeneim@gmail.com>; "Author" <author@noreply.github.com>
Тема: Re: [ninenines/cowboy] cowboy leaks RAM when handler crashes (#1029)

I will have to try but I'm not quite sure how it could leak anything in the first Cowboy version since nothing is kept around. It's probably just a case of GC being too slow, and should be easily fixed by configuring the maximum number of requests you can do on one connection (defaults to 100).
In Cowboy 2 it's possible that such issues still remain at this time as little has been done to properly test streams handling. But otherwise the same configuration still exists.

**Comment by essen** [comment]
This and that it also does it with 1.x is pretty weird.

**Comment by brigadier** [comment]
It's actually the `error_logger` process which grabs memory with each error and grows until OOM. Well known issue, talked about in the Erlang in Anger.  The solution is to use `lager` instead.

"This is especially true of user-generated log messages (not for errors), and for crashes in
large processes. For the former, this is because error_logger doesn’t really expect arbitrary
levels of messages coming in continually. It’s for exceptional cases only and doesn’t expect
lots of traffic. "

**Comment by essen** [comment]
Sure. But I don't want to force a dependency on lager. I'm sure error_logger could be fixed to avoid such issues also, as seen by some of the recent patches. Closing, thanks!

**Comment by ferd** [comment]
The usage of lager I recommended in EiA is certainly not the only way to go about things:

- replacing error_logger handlers for some that drop larger cowboy handler messages from crashes (or truncates them)
- using lager (or a similar lib) at the top level of the project, since they're able to redirect logs
- removing crash logs going to disk since for large datasets those can be much slower

and so on.

I do agree with the decision to close the issue, just wanted to add some details for other possible avenues.
