### ISSUE TITLE
Server initiated WebSocket close does not wait for client close handshake before closing the socket

### ISSUE THREAD

**Issue by yosh** [ninenines/cowboy#1044]
After sending down a close frame to the client, the server code closes the socket immediately, without waiting for the client to respond. This violates the WebSocket specification: https://tools.ietf.org/html/rfc6455#section-7.1.2

> Once an endpoint has both sent and received a Close control frame, that endpoint SHOULD Close the WebSocket Connection

I noticed this while trying to return a status code down to the client (in this case, [SocketRocket](https://github.com/facebook/SocketRocket)). SocketRocket considers a TCP socket closure before it can send its close handshake as an abnormal socket termination, and thus does not propagate up the status code from the close frame to the calling code, and instead returns an error code. As mentioned above, this is compliant with the WebSocket specification.

I'm happy to submit a patch addressing this, but I'd like some guidance on behavior:

- Per the spec, after sending a close frame, there should no longer be any writes to the socket. After receiving the close handshake, it can close the socket. Due to the asynchronous nature of cowboy, data frames may still be received by the handler process after the close frame is sent, and a handler could still attempt to send some data down in response to these frames. What should happen here? We could return an error back up somehow, or silently drop the incoming frames, or silently drop any outgoing frames, or consider this behavior buggy and crash the process. Or make this configurable among some or all these options. Thoughts?

- There probably should be some sort of timeout option to shutdown things in case the close handshake is not received. Should this be configurable on its own, or tied in with the init handshake timeout? If the former, what should the default be?

**Comment by essen** [comment]
It does not violate the spec. SHOULD is not an absolute requirement, it can be ignored if there are good reasons. In Cowboy's case the reason is to not want to keep around connections unnecessarily. In the spec it means we are not closing the connection _cleanly_.

There is however an issue in your client, since all the spec in 7.1.5 says is:

```
   The WebSocket Connection Close Code_ is
   defined as the status code (Section 7.4) contained in the first Close
   control frame received by the application implementing this protocol.
```

It doesn't say anywhere that the connection needs to be cleanly closed to give a close code to the application, just that the first close frame contains it. Also read the rest of this section as it explains what the close code is when the close frame doesn't contain a code, or the connection was closed without a close frame. In *all* cases there's a close code defined. In our case it's the one sent by the server.

Closing, thanks!
