### ISSUE TITLE
real init function for acceptors

### ISSUE THREAD

**Issue by manuel-rubio** [ninenines/cowboy#1137]
I was wondering if there are possibility to run code to put in the state before the acceptor accepts the connection. For example:

```erlang
%% running in a pre-accepting stage
init(Req, Opts) ->
    %% perform some initializing tasks and create State
    {ok, Req, State}.
```

In this way we can reduce the latency for an entry call if we can do some code execution before the request arrive to the system.

**Comment by essen** [comment]
This is something I thought a lot about before. The thing is, this will only matter for applications that have little traffic. If you're accepting connections without ever stopping, you will just move the operations to before the accept is performed, and the latency will not change because the socket will just wait longer before it is accepted.

**Comment by manuel-rubio** [comment]
Maybe you're right, I thought maybe increasing the number of acceptors it could help to use only the prepared ones. But you're right, if the load is greater than the number of acceptors the advantage is lost.

Anyway, I think if the load is greater than the number of processes then we have the same situation as if we haven't this so, maybe it's worthy to have it after all.

**Comment by essen** [comment]
Too many acceptors also has a cost so you can't increase it much, otherwise you end up with lesser performance.

If you still think it's worth having, then please provide a real use case (ie what you would init there) and open a ticket on the correct repository (Ranch). Closing this one.
