### ISSUE TITLE
Incorrect GitHub link on hex.pm page

### ISSUE THREAD

**Issue by cpjolicoeur** [ninenines/cowboy#1140]
The GitHub link on the cowboy package on hex.pm (https://hex.pm/packages/cowboy) links to the ranch project on GitHub (https://github.com/ninenines/ranch) and not cowboy (https://github.com/ninenines/cowboy).

**Comment by essen** [comment]
I am not the maintainer of the hex package.

**Comment by ericmj** [comment]
@essen Would you like to be the maintainer? I think that would make it easier for everyone, less chance of issues like this and new releases are published immediately.

**Comment by essen** [comment]
I don't have time. This is open source, everything shouldn't fall down to just the one guy. People who need this package should be the maintainers.

**Comment by ericmj** [comment]
> I don't have time. This is open source, everything shouldn't fall down to just the one guy. People who need this package should be the maintainers.

The problem is that package metadata is not provided by the project or an easy way publish it so the package maintainers have to build it each time a new version is released, and they have to watch the projects to know when releases are made. That means mistakes like this will happen and the package will lag behind the project on important bug and security fixes.

**Comment by essen** [comment]
Anyone can setup a repository, subscribe to the RSS tag for the releases and publish to hex when they happen. That's pretty much how all curated package repositories work. It's not rocket science.
