### ISSUE TITLE
Cowboy setup for Mutual TLS (or 2-way TLS.... client certificate for auth)

### ISSUE THREAD

**Issue by ulutomaz** [ninenines/cowboy#1197]
I am struggling with Cowboy setup and can't really find a solution. I would really like to set Cowboy in a way that would allow me to have client certificates for authentication. Is this possible in latest Cowboy?

Thanks

**Comment by essen** [comment]
In Cowboy 1.0 yes, in Cowboy 2.0 it's not possible anymore, it was temporarily cut due to the architecture changes and will be added back soonish, probably right after 2.0 is out. There's a way to do it still, but it involves writing a wrapper above the protocol code (get the certificate before handing control to Cowboy, save it in options) and a stream handler (move the certificate from options to Req).

**Comment by essen** [comment]
This is now fixed in the most recent commit. Please see https://github.com/ninenines/cowboy/issues/1147 for more details.
