### ISSUE TITLE
SSE fails if cowboy_compress_h is added to stream_handlers

### ISSUE THREAD

**Issue by leoliu** [ninenines/cowboy#1238]
I was thinking enabling compression this morning and enabled it via:

```
stream_handlers => [cowboy_compress_h, cowboy_stream_h]
```

after the change, REST handlers worked great with reduced content-length header. But SSE handlers using cowboy_loop failed. The browser was not receiving any events.

I traced the erlang node to make sure messages were being pushed to the SSE request pid.

OTP 20.1.5, cowboy 2.1 with http2, centos 7.4

**Comment by essen** [comment]
I think that's because the events are too small and get buffered by zlib instead of being sent immediately. I am not sure what the correct fix for this is but it probably involves flushing the buffer for every data command, problem is identifying when it makes sense to do this as we want this in specific situations and not when streaming a normal response body.

**Comment by essen** [comment]
I'm thinking of adding two things:

* An option to disable buffering entirely for `cowboy_compress_h` for all requests.
* A way to modify that option on a per-request basis, perhaps by having your loop handler send a message.

That way you can either buffer by default and disable it where needed, or vice versa. I don't think we'll get much better.

**Comment by essen** [comment]
I've added an option to control buffering in my local copy, and changed the default to not buffer (with a small compression cost of course).

I still think adding a way to change options on the fly would be useful so I will add this as part of #1292.

Closing, thanks!
