### ISSUE TITLE
Cowboy_rest issues accepting single charset with content_type_provided/charsets_provided 

### ISSUE THREAD

**Issue by psytale** [ninenines/cowboy#1245]
Appears in 1.* and 2.* to the best of my knowledge.

I have a cowboy_rest endpoint which I want to only provide a single charset. So I expect clients to be specifying their wanted content-type with a charset as a parameter or using the `accept-charset` header. E.g. `accept: application/json;charset=utf-8` or `accept: application/json accept-charset: utf-8`.

The following code does that however it results in a duplicate `charset=utf-8` if they request `application/json;charset=utf-8`
```
content_types_provided(Req, Ctx) ->
  { [ {{<<"application">>, <<"json">>, []}, process_get}
    , {{<<"application">>, <<"json">>, [{<<"charset">>,<<"utf-8">>}]}, process_get}]
  , Req, Ctx}.

charsets_provided(Req, Ctx) ->
  {[<<"utf-8">>], Req, Ctx}.
```
Alternatively I can provide only `{<<"application">>, <<"json">>, '*'}` and always get the correct content-type in the response but a client could request `application/json;charset=ISO-8859-1` and suddenly get a response in the wrong charset instead of a 406 which is not desired.

**Comment by essen** [comment]
The charset is not supposed to be supplied in Accept, and you therefore should not have it in `content_types_provided`. There shouldn't be an issue if separate headers are used.

**Comment by psytale** [comment]
The use seems fairly widespread and https://www.iana.org/assignments/media-types/media-types.xhtml specifies it as a valid parameter but it is perhaps non standard.

**Comment by essen** [comment]
The charset parameter is standard but in HTTP it's handled separately via the accept-charset header.

**Comment by psytale** [comment]
https://tools.ietf.org/html/rfc7231#section-5.3.2 probably shouldn't list it as an example then. 

But thanks for the quick response, recommended way of dealing with legacy clients would be to accept '*' and set the charset using the correct callback?

**Comment by essen** [comment]
Actually I went back to reading and I think it makes sense to have both accept with charset and accept-charset separately, as they have similar purposes but not exactly the same. When you have a charset in the accept header it can be used to indicate that you prefer a media type with one charset and not the header, while the accept-charset header is applying more generally (ie to all the text media types).

I think these changes need to happen:

* When a charset is provided in the selected media type and the resource media type we skip the accept-charset header and `charsets_provided` (we only check accept-charset for media types with no charset).
* When a charset is provided in the selected media type but the resource didn't provide one (ie it used `'*'`) we check this charset against what `charsets_provided` returns.
* Otherwise we keep the current behavior.

Thoughts?

**Comment by essen** [comment]
I'm also wondering about this automatic addition of the charset to the returned media type, I think it does not make sense for all media types as it's specific to text.

**Comment by psytale** [comment]
I think that sounds like a good approach, and a great point about non text media. I guess this should only be for `text/*` media, my example of application/json was poorly chosen.  

Only case I can think of that is not handled is an accept header for a charset that is neither supported by the `content_types_provided` or `charsets_provided`. We'd end up matching on the `'*'` or should there be some logic to enforce a hard match against the charsets in `charsets_provided` if a charset is provided in accept and matched against a `'*'` to properly return a 406?

**Comment by essen** [comment]
I believe that's the case in my second point. `content_types_provided` has a match only when `'*'` is used, therefore we check `charsets_provided` using the charset from the matched accept value, and in that case we get a 406 yes.

**Comment by psytale** [comment]
Ah ha, missed that sorry, interested in a PR implementing this?

**Comment by essen** [comment]
PRs are always good but there's no hurry I probably won't merge before next year.

**Comment by essen** [comment]
All done, push soon, thanks!
