### ISSUE TITLE
idle_timeout triggered while streaming body

### ISSUE THREAD

**Issue by djustinek** [ninenines/cowboy#1278]
Stream body that lasts over 1 minute triggers idle_timeout in http handler even though packets are constantly being sent.

**Comment by essen** [comment]
I think that's working as intended. The idle timeout is about the client not showing signs of being alive (a shortcoming of HTTP/1.1 really). So I would say you need to increase this option to whatever upper limit you're willing to accept.

**Comment by essen** [comment]
I don't disagree but the feature is not for your scenario, it's instead for scenarios like SSE where data goes into the socket much slower and it therefore can take a long time before the kernel buffers get full and an error is propagated to Erlang.

**Comment by SergejJurecko** [comment]
Then idle_timeout should be a http2 configuration option not global. Default values should not result in wrong behavior.

**Comment by essen** [comment]
It's HTTP/1.1 not HTTP/2. No such issue with HTTP/2. The option is necessary because the HTTP/1.1 protocol is poorly designed and does not protect you from TCP half-open problems.

There's also no default that would lead to a correct behavior, it's either "allow long responses to complete" or "ensure we don't have too many zombie connections around". The current default is good because very few users have handlers that take more than one minute to send their response.

**Comment by jimdigriz** [comment]
This is affecting us with `cowboy_loop` on 2.4 and 2.5.

Our use case is the client requests a log file, and we chunk body it to the client as the node receives data from all the other nodes in the distribution.  Another use case I could think of is if someone is requesting a report and the backend takes more than 60s to reply.

For HTTP/1.x, I can't imagine why you would want `idle_timeout` to ever apply when currently you are actively processing a request.  The client sent the headers and is waiting for a reply.  If you need a watchdog to kill long requests, then the developer can already do this with either `timer:kill_after()` or something akin to `spawn_link(fun() -> timer:sleep(...), exit(watchdog) end)`.

Fortunately for us, there is no urgency to get this resolved as we moved the major user of our log streaming service onto an HTTP2 enabled cURL binary, others may not be able to so easily (thinking of Perl, PHP, ... where libcurl is not being used).

**Comment by essen** [comment]
> For HTTP/1.x, I can't imagine why you would want idle_timeout to ever apply when currently you are actively processing a request.

Because some requests never end. For example those that send `text/event-stream` as a response. The handler may never end (and rarely send data), and there is no way to know the client is still there. It is to deal with these cases that the option exists.

It would probably be nice to be able to change options for a single connection, that I could get behind. That way one could identify they're going to stream for a long time and change the setting only for this connection.

**Comment by jimdigriz** [comment]
Would not using `high_watermark`/`high_msgq_watermark` in `inet` be a better option?  If the sends to gen_tcp stalls for 60s, that would be a good reason to timeout the connection.

**Comment by essen** [comment]
The problem is that on these requests there might not be a send in a very long time too.

**Comment by essen** [comment]
I don't have a problem, in my use cases Cowboy is working perfectly as expected. I do not need to stream data for more than a minute outside text/event-stream, which can reconnect without problem.

If you need to stream data for more than a minute, but only on some requests, then the command I'm mentioning would work for you too, since you'd be able to benefit from the timeout in all requests except those that will take a long time.

TCP keepalive is unfortunately not a silver bullet, because it doesn't work across intermediaries. But if it works in your case, Cowboy doesn't prevent you to use it and you can disable the idle_timeout entirely.

**Comment by essen** [comment]
FYI: 2.6 will include a way to increase the `idle_timeout` of HTTP/1.1 connections on a per-request basis. See https://github.com/ninenines/cowboy/issues/1292#issuecomment-438972531
