### ISSUE TITLE
Know which handler served the request

### ISSUE THREAD

**Issue by hachreak** [ninenines/cowboy#1280]
I was looking how to best use `cowboy_metrics_h.erl` to get global useful metrics like `#req/sec`, `http status counter`, `avg/min/max request time`.

And I was wondering if could be useful also to have all these metrics but per route/handler.
E.g. to know how many requests to `/users/[:id]` that return 404.

Do you think there is a easy way to retrieve this information from `cowboy_metrics_h.erl` callback?

Thanks a lot :smile:

**Comment by essen** [comment]
There isn't, and I'm surprised there is no open issue about this. It's been brought up a few times. I don't have a good solution for this because routing happens much later in the request processing. You can always call `cowboy_router` of course but that's not terribly efficient.

**Comment by essen** [comment]
Rather than trying to solve "how to find the handler in metrics" perhaps instead a more general interface should be added that allows attaching some metadata to a stream and that the metrics handler can use. Maybe something like `cowboy_req:set_stream_metadata(Name, Value, Req)` which sends a message like `{metadata, Name, Value}` to the relevant stream handlers.

**Comment by essen** [comment]
I will try to squeeze this into 2.6 tomorrow. I am documenting `cowboy_metrics_h` so it'd be good to have it solved. The new command `{set_options, Opts}` is probably the best way to implement this.

**Comment by essen** [comment]
Heh to be honest I'll keep cowboy_metrics_h docs for after the release, there's some more stuff to be tested first.

**Comment by essen** [comment]
Done in most recent commit. f673e191b30ab440440c924476bb03000fff52c6
