### ISSUE TITLE
May I reset idle_timeout value after init function?

### ISSUE THREAD

**Issue by suzuiyuegjy** [ninenines/cowboy#1292]

**Comment by suzuiyuegjy** [comment]
when use cowboy_websocket module

**Comment by essen** [comment]
What do you mean by reset?

**Comment by suzuiyuegjy** [comment]
set idle_timeout a value before login verified, ande reset it to Infinity after login verified

**Comment by essen** [comment]
It's not currently possible.

**Comment by suzuiyuegjy** [comment]
@essen is there any way to change cowboy_websocket opts except in init callback?

**Comment by essen** [comment]
No. I'm wondering why you don't verify in init though? Is it a login that's protocol-specific rather than via HTTP?

**Comment by suzuiyuegjy** [comment]
@essen Yes， it is verified with token transmitted using protobuf.

**Comment by essen** [comment]
OK, sounds like something useful to have, I'll consider it when i revamp the interface to allow for more commands. Won't be for a few versions though.

**Comment by suzuiyuegjy** [comment]
OK, Thank you for your support.

**Comment by AndreyKlimchuk** [comment]
@suzuiyuegjy Hi, if it could help, my workaround for this is setting timer in init callback and keeping some status in state, if timer is triggered and status is 'not authorized' (message with auth token was not received), handler is stopping, otherwise timer's message is ignoring.
I agree that proposed feature will be helpful.

**Comment by essen** [comment]
I will add stream handler and Websocket handler commands that will look like this:

``` erlang
{set_options, Opts=#{}}
```

It will allow changing *some* options, not all (and I will start with a small number of options and work from there).

As part of this ticket I will add support for changing at least two options:

* `compress_buffering` for the compression stream handler, so that one can use efficient compression most of the time and disable it on a case by case basis; and
* `idle_timeout` for HTTP/1.1 and Websocket, so that one can increase it specifically for some use cases (HTTP/1.1 when a request will take a long time to respond to, Websocket for your use case)

**Comment by essen** [comment]
I have added all this. I will not document these new commands yet, maybe I'll allow updating more options first, and I also would like to receive some feedback, so try 2.6 when it's out and tell me! Pushing later today. Closing, thanks!
