### ISSUE TITLE
How to install GNU make 4.x on the CentOS 7

### ISSUE THREAD

**Issue by mihongkun** [ninenines/cowboy#1316]
# make
erlang.mk:30: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
erlang.mk:30: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 ERLC   hello-world_app.erl hello-world_sup.erl
src/hello-world_app.erl:1: bad module declaration
src/hello-world_app.erl:2: no module definition
make[1]: *** [ebin/hello-world.app] Error 1
make: *** [app] Error 2

**Comment by essen** [comment]
It's not a requirement, my test environments for CentOS 7 currently have Make 3.82.

Your issue comes from the fact you named your application `hello-world` instead of `hello_world`. The character `-` is not valid for module names and that ends up causing the problems you see.

**Comment by NobbZ** [comment]
> The character `-` is not valid for module names

This is not true, you need to quote the modulename then (which I do anyway, as I think its a good habbit):

```plain
$ cat foo-bar.erl
-module('foo-bar').

-export([f/0]).

f() -> works.
$ erlc foo-bar.erl
# exit code zero, no output
```

**Comment by essen** [comment]
That's true for Erlang, that's not true for Erlang.mk templates.

**Comment by NobbZ** [comment]
Ah, Okay, so just another reason to stick to `rebar3` then.

**Comment by essen** [comment]
Well, yes and no. Rebar3 won't help if you want your application named `hello-world` because Erlang does not allow application names to have a `-` character, when Erlang looks at application paths everything after the first `-` is considered to be the version. So if you try to name your application `hello-world` then Erlang will think the application name is `hello` when resolving it, and this creates all sorts of issues.

The `-` is best avoided entirely.

**Comment by NobbZ** [comment]
Yes, application names are different, but we talked about modulenames before.

**Comment by essen** [comment]
The error above is due to the application name having the `-` and Erlang.mk using the application name as part of the bootstrapped modules (`$APP_app` and `$APP_sup`). It doesn't stop you from having modules with `-` beyond that.
