### ISSUE TITLE
Cannot send custom value in content-length when sending empty body

### ISSUE THREAD

**Issue by hauleth** [ninenines/cowboy#1328]
`HEAD` requests requires that the response should be the same as `GET` request on the same path, but without any body [[ref](https://tools.ietf.org/html/rfc7231#section-4.3.2)]. Currently it is impossible to send custom `content-length` value in that header in responses other than `204` (#1153) while it should be possible in some cases.

**Comment by hauleth** [comment]
Wow. It seems to work, however question is how to handle that when the budy computation is expensive, but getting size itself is quite cheap. For example sending a file that need to be fetched from slow device.

**Comment by essen** [comment]
If you use sendfile Cowboy will not fetch the file. If you need another solution, I'd say `stream_reply` with content-length + one final empty `stream_body` (that will be ignored because the method is HEAD) ought to work.

**Comment by essen** [comment]
Note that the final `stream_body` is not necessary if the handler exits immediately.

**Comment by hauleth** [comment]
Ok, thanks.

**Comment by gottfrois** [comment]
I encounter the same issue. Just to give you a bit of context, I use `Plug.Conn` with the default cowboy adapter and when trying to respond to a `HEAD` request with a custom `content-length` header and an empty body, I get a `content-length` of `0` instead of my default value.

@essen I'm not sure I get your suggested work around above.
> Just behave the same as GET and the content-length will be set accordingly.

I have tried to override the plug conn `method` from `HEAD` to `GET` but with the same results.

Some code I have tried:

```elixir
conn
|> Plug.Conn.put_resp_header("content-length", "12")
|> Plug.Conn.send_resp(200, "")
```

Output with curl:

```sh
$ curl -i -I "http://localhost:8080/hello-world.txt"
HTTP/1.1 200 OK
cache-control: max-age=0, private, must-revalidate
content-length: 0
date: Mon, 23 Mar 2020 16:34:09 GMT
server: Cowboy
```

And same thing when overriding the `method`:

```elixir
%{conn | method: "GET"}
|> Plug.Conn.put_resp_header("content-length", "12")
|> Plug.Conn.send_resp(200, "")
```

Any suggestions would be greatly appreciated.
Thanks 😃

**Comment by essen** [comment]
I don't know Plug but if you send a response with no or empty body then the content-length will be set to 0. Cowboy needs to know what body you would have sent in order to calculate the length, and when sending a full response in a single call Cowboy will set the content-length itself and it cannot be overriden because it is important for framing.

If you need to send a file, as mentioned above, you should proceed as normal and pass the sendfile tuple in the response as Cowboy will not read the file when responding to HEAD requests. It will only get stats.

The alternative is to use `cowboy_req:stream_reply` and provide the content-length manually. Here it's allowed but note that you will need to disable chunked transfer-encoding for HTTP/1.1 (you can disable it dynamically for a single response).

**Comment by gottfrois** [comment]
Thanks for the quick answer @essen!

Isn't this behavior violating the RFC when the HTTP request is a `HEAD`? Since it's used for obtaining metadata about the resource without transferring actual resource data over the `body`.

Reading the RFC, I was under the impression that a `HEAD` request, provided with a `content-length` should use it and not override it to `0` since, by definition, the `body` will be empty for such HTTP method.

I would agree though that content-length should be set to equal the body size for a `GET` request.

As for the answer about the file, I'm not dealing with a file at all, simply proxying a response from a downstream HTTP service (AWS S3) which sets the `content-length` to some value and respond with an empty body.

**Comment by gottfrois** [comment]
I gave a try to `cowboy_req:stream_reply` which is the implementation behind `Plug.Conn.send_chunked/2`.

I get my custom `content-length` value! 🎆 
Can you just elaborate a bit more about my need to "disable chunked transfer-encoding for HTTP1/1"? I'm not sure what this is about.

Thank you for your time.

**Comment by essen** [comment]
> Isn't this behavior violating the RFC when the HTTP request is a `HEAD`? Since it's used for obtaining metadata about the resource without transferring actual resource data over the `body`.

You answer your own question here. **without transferring actual resource data**. Cowboy doesn't transfer that data. But Cowboy still needs to know about it in order to compute the response.

> Reading the RFC, I was under the impression that a `HEAD` request, provided with a `content-length` should use it and not override it to `0` since, by definition, the `body` will be empty for such HTTP method.

Well you're using Cowboy, not the RFC. This is purely an API concern. When you do `cowboy_req:reply` Cowboy sets the content-length. It's not about HEAD or GET, it applies to all methods.

> > When using HTTP/1.1, the Cowboy adapter will stream the response instead of emitting chunks if the content-length header has been set before calling send_chunked/2.

I forgot about that, so ignore my comment about chunked.

**Comment by gottfrois** [comment]
Thanks again for your quick answer!
I think I can get around by using `cowboy_req:stream_reply` then.
