### ISSUE TITLE
cowboy_req:stream_body/3 needs a backpressure mechanism

### ISSUE THREAD

**Issue by jvoegele** [ninenines/cowboy#1376]
We have a Phoenix application that generates very large API responses (approaching 1Gb in size) in both JSON and CSV formats. To keep memory usage down, we are streaming these large responses back to the client using `Plug.Conn.send_chunked` and `Plug.Conn.chunk`, which in turn calls `cowboy_req:stream_body/3`.

The problematic behavior that we have experienced with this is that, because `cowboy_req:stream_body/3` does not have any sort of backpressure mechanism, the stream is fully materialized almost immediately and memory usage spikes to hold the entire stream in memory. Furthermore, the `cowboy_clear:connection_process` process gets overloaded with millions of messages in its mailbox, and hence slows down to a crawl.

I created an issue in the GitHub issue tracker for the `plug_cowboy` project, and rather than repeat the lengthy analysis here I will simply refer to that issue for further detail: https://github.com/elixir-plug/plug_cowboy/issues/10

The upshot is that there needs to be some coordination between `Plug.Cowboy.Conn.chunk/2` and `cowboy_req:stream_body/3` to provide backpressure and prevent the spike in memory usage and the extreme performance degradation. @josevalim suggests that Cowboy could provide some sort of ping operation that would return a pong to the caller once it receives the ping from its mailbox. See this link: https://github.com/elixir-plug/plug_cowboy/issues/10#issuecomment-485133346

Does that seem like a reasonable approach, or do you have any other ideas for addressing this issue?

Thanks!

**Comment by essen** [comment]
In Cowboy 1.0 the `chunk` function was synchronous because it was writing directly to the socket. I don't have a problem making the 2.0 equivalent's `stream_body` synchronous as well. The implementation would then be restricted to the `cowboy_stream` related modules.

**Comment by essen** [comment]
As a workaround in the meantime you can always check the size of the mailbox of the connection process before calling stream_body again. Should be cheap.

**Comment by josevalim** [comment]
While I am totally fine with `chunk` being `sync`, it is worth saying the advantage of a `sync`/`ping` operation is that it allows us to be more efficient. Instead of syncing on every write, I can write 10 or 100, and only then wait until that is flushed.

`message_queue_len` unfortunately uses locks, I am not sure of the granularity of the lock though.

**Comment by essen** [comment]
As a workaround I don't think it'd be a big issue to check it every few stream_body calls and sleep between tries. Obviously not what the real solution should look like.

My problem with a separate function is the user has to worry about it. Note that if stream_body is synced, that doesn't necessarily mean that stream_body will return only when the data is written to the socket. Rather it should return IF we can write more data to the socket, which is an entirely different matter, particularly for HTTP/2. So this would allow Cowboy to optimize without the user having to worry about it.

**Comment by jvoegele** [comment]
> As a workaround in the meantime you can always check the size of the mailbox of the connection process before calling stream_body again. Should be cheap.

I have implemented exactly this workaround in our application code, and while it is not an ideal solution it does circumvent the problem.

**Comment by essen** [comment]
I think for HTTP/1.1 there isn't much that can be done other than make it wait for a message back before stream_body returns. So what would happen would be roughly: call stream_body, cowboy_stream_h sends message back (resuming the handler) and right after that returns the data command that results in the socket write (done concurrently with whatever the handler is doing). The write is synchronous therefore this would act as backpressure and ensures we can always have the next message already in the mailbox.

For HTTP/2 a scheme where the protocol code would tell cowboy_stream_h to pause the handler (by not sending the message back for a while) would also be necessary because we do not necessarily send data immediately, it depends on the connection/stream flow control windows. Cowboy would probably need an option to define how much data we accept to buffer before we pause stream_body calls in the handler. HTTP/2 would therefore have greater potential for optimization, and I think that's fine.

A question then becomes should we have a timeout while waiting for the message back in stream_body. If the code is working well I don't think we do since the process will eventually either resume or be killed, but in case we do we can always add a stream_body function that takes options.

**Comment by essen** [comment]
I've started work on this.

**Comment by essen** [comment]
The solution I'm going with is that there's a new option `max_stream_buffer_size` which, when we try to send data exceeding that soft limit, the stream handler gets an info message indicating we went above. And when we go back below, we get a similar message. This lets the stream handler control whether to send the ack message under these conditions.

The info message in question will stay undocumented for now. Not sure it should be called an "alarm" or an "internal event" yet, because we have no other similar messages at the moment.

I've got most of the code done but the relevant test is not working yet for HTTP2.

**Comment by essen** [comment]
I've opened https://github.com/ninenines/cowboy/pull/1402 with a fix for this. It's still lacking documentation for the new option and has some `ct:pal` left around so I can see it being used when running tests (it's used). Please try it and provide feedback.

I'm not sure whether it should be mandatory or optional. Considering I/O is often the weak link leaving it mandatory is probably not a problem. Someone with special needs could always work around it anyway.

**Comment by essen** [comment]
I've merged the changes. Closing, thanks!

**Comment by jvoegele** [comment]
I can confirm that these changes have fixed the original problem for me. Thanks, @essen!
