### ISSUE TITLE
logger:level is an unknown type on OTP 20

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/cowboy#1406]
dialyzer analysis, when importing `cowboy` 2.6.3 on OTP 20, shows that e.g. `cowboy_stream.erl`'s type `commands()` references OTP (21+ only) type `logger:level()` which is an unknown type.

Would you accept a PR to have e.g. `logger_level()` as a local type then made OTP version-dependant?

Something like
```
-ifdef(OTP_RELEASE).
-type logger_level() :: logger:level()
-else.
-type logger_level() :: emergency | alert | critical | error | warning | notice | info | debug.
-endif.
```

**Comment by essen** [comment]
No, types should always target the most recent OTP version, and Dialyzer is only tested against my projects using the most recent OTP version in order to get the most recent improvements in the Dialyzer logic.

It may not seem like much in this particular case but it very much is in others, like `ssl` types which change every other release. It is not really worth the cost.

Thanks anyway!
