### ISSUE TITLE
Documentation ambiguity: meta

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/cowboy#1412]
https://ninenines.eu/docs/en/cowboy/2.7/guide/migrating_from_1.0/ says:

> The functions cowboy_req:meta/2,3 and cowboy_req:set_meta/3 have been removed. The Req object is now a public map, therefore they became unnecessary.

However, https://ninenines.eu/docs/en/cowboy/2.7/guide/req/ says:

> Modifying the Req object, while allowed, is not recommended unless strictly necessary.

It then goes on to talk about namespacing the fields, if we do add any.

This is ambiguous. Either we can throw (appropriately namespaced) random fields in there or we can't. I think the "unless strictly necessary" warning in the 2.7 guide should be relaxed slightly.

Or maybe some guidance on what other, preferred, mechanisms there are to replace meta? Maybe some forms of meta are more appropriately dealt with in stream handlers or the env in middleware?

Specifically in this case, we're "tagging" the request with (let's say) the user ID, so that we can pick it up again in access logging (presumably using #1251 or similar).

**Comment by essen** [comment]
Not sure what's ambiguous, the first link talks about functions that are no longer necessary because Req is no longer a record. It doesn't say anything about use cases, just that you can do the same as before without those specific functions.

The note about modifying is not just about metadata, but about modifying existing fields as well. Either way it's not recommended in the general case where you have a State you can use to store things in.

There are cases where it's perfectly fine to modify the Req or add new information. Yours is one. Caching some information extracted from the Req is another, like what `cowboy_rest` is doing.

**Comment by rlipscombe** [comment]
Maybe ambiguity is the wrong word then. It's the strength of "Modifying the Req object, while allowed, is not recommended unless strictly necessary." that bothers me, I guess.

If it were more "The Req object is a map, so you can add your own fields to it (make sure they're namespaced). You should only do this if you need to persist information in the request past the lifetime of the handler. For information specific to the handler, use the State.", I think it'd be clearer.

It's not a hill I'm prepared to die on, though. It's just that I'm coming at the new documentation fresh (as mentioned in another issue, we're moving from 1.0.4 to 2.7.0, which is a massive jump), and there are some bits that I think could use more context and gentle advice/guidance to the correct solution.

Actually, maybe some more examples would help with some of this...? You could open a bunch of issues and mark them with 'help-wanted'. I could try to help out with a couple.

**Comment by rlipscombe** [comment]
But, while I'm here, I'm just going to throw in a heartfelt thanks for all of the work you've done on cowboy and ranch.

**Comment by essen** [comment]
Feel free to send PRs to update or clarify the guide, I've not had much time to update it since at least 2.0.

**Comment by essen** [comment]
I'm applying the following change:

``` patch
diff --git a/doc/src/guide/req.asciidoc b/doc/src/guide/req.asciidoc
index 9d04ce0..fad5760 100644
--- a/doc/src/guide/req.asciidoc
+++ b/doc/src/guide/req.asciidoc
@@ -48,10 +48,12 @@ Any other field is internal and should not be accessed.
 They may change in future releases, including maintenance
 releases, without notice.
 
-Modifying the Req object, while allowed, is not recommended
-unless strictly necessary. If adding new fields, make sure
-to namespace the field names so that no conflict can occur
-with future Cowboy updates or third party projects.
+Modifying the Req object is allowed, but extra caution
+must be applied when modifying existing fields. You can
+add as many new fields as necessary, however. Just make
+sure to namespace the field names so that no conflict
+can occur with future Cowboy updates or with third party
+projects.
 
 === Introduction to the cowboy_req interface
 
```

It should be clearer. There is no need to mention the `State` I believe, since depending on the application the `Req` might be a better place for data (for example that's what I do in Farwest in order to avoid passing around two separate variables everywhere).

Tell me what you think and I'll push.

**Comment by rlipscombe** [comment]
s/applied/used/

But otherwise, looks good to me. Thanks.

**Comment by essen** [comment]
Thanks!
