### ISSUE TITLE
Don't fail when server has {compress, true} enabled and receives a malformed Accept-Encoding header 

### ISSUE THREAD

**Issue by mracos** [ninenines/cowboy#1427]
Regarding this comment here, https://github.com/ninenines/cowboy/blob/63b17e4edf666d995ec86cdcda17a62ba5ebc423/src/cowboy_compress_h.erl#L75

Not sure how to solve this or even if it is still a desirable thing to be done, should we just ignore the header on these situations and not compress the response by maybe wrapping this block in a `try/catch`? Should we return a `406 NOT ACCEPTABLE`? WDYT?

---

Last but not least, thank you for all the awesome work you do ❤️

**Comment by essen** [comment]
Did you run into this in the wild?

The RFC doesn't say but generally we're free to ignore the accept headers so I would suggest doing so in this case and not compressing.

**Comment by mracos** [comment]
So, _Kinda_, hahaha
I had to do something that was exactly what `cowboy_compress_h` already does so in order to understand if I could use I went on to read the source code. 😄

So I'll give this one a shot and come up with a patch, does that sound reasonable?

**Comment by essen** [comment]
Sure. Make sure to leave a comment explaining (since this isn't mentioned in the RFC) and add a test.

Found this by the way: https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.3.4 So error handling really is application specific. I think not throwing an error is the better choice for this particular case.

**Comment by essen** [comment]
Done, thanks.
