### ISSUE TITLE
TLS handshake continue

### ISSUE THREAD

**Issue by zuiderkwast** [ninenines/cowboy#1454]
Is there a way to make cowboy fetch a certificate by calling some custom code at the time of each TLS handshake?

There is the ssl option `{sni_fun, fun()}` but it is not called if the client doesn't send SNI.

Some interface using handshake hello/continue would probably work, I guess.

**Comment by essen** [comment]
You need to write a custom Ranch transport and use it instead of `ranch_ssl`.

**Comment by zuiderkwast** [comment]
It's been added to `ranch_ssl` already in https://github.com/ninenines/ranch/pull/271.

I think it's rather `cowboy_tls` which needs to be adapted slightly, specifically the line `{ok, Socket} = ranch:handshake(Ref),` because `ranch:handshake/1` may actually return `{continue, _}` here if `{hanshake, hello}` is specified in the TLS options.

I was thinking about passing an option `{handshake_continue_fun, fun(...) -> {continue, TlsOptions} | cancel}` through to cowboy_tls, which would be called if `ranch:handshake/1` returns a continue tuple, but since you closed the issue, I assume an official addition for this use case isn't wanted in cowboy. Is that right?

**Comment by essen** [comment]
Yes in Ranch 2.0 it'll allow using the multi step handshake, but I'm not sure Cowboy should do anything about it. You're the first to ask. I'm also not sure what Cowboy should do about options that require Ranch 2.0.

Simpler solution for your case would probably to have a custom transport on top of `ranch_ssl`, forwarding all calls except for the handshake, but it's also possible to use a custom module instead of `cowboy_tls`. Or patching Cowboy of course.

If the feature is more popular or there's commercial interest I can consider adding it, and of course PRs are always welcome, but my schedule is fairly limited due to current events so it'll take a while before it may be merged.
