### ISSUE TITLE
Tear-down the connection

### ISSUE THREAD

**Issue by juise** [ninenines/cowboy#1474]
Hello!

I stumble upon the interesting (for me) behavior, a few of most http requests are failed with the reason "socket_closed_remotely".

I have the erlang client which uses httpc (it has connection manager) and cowboy 2.6.3. In the tcpdump tcp trace (attached to issue [from_client.pcap.zip](https://github.com/ninenines/cowboy/files/5379010/from_client.pcap.zip)), I see, that httpc client sends http requests, the httpc connection manager route that requests into established connections. And after some requests/replies, cowboy decide to close the connection, and in tcp trace, I see the [FIN, ACK] from it. But, after ~16 microseconds, httpc sends request into connection, and after that replies with [FIN, ACK] and receives [ACK] back from cowboy. As the result, the last request failed with "socket_closed_remotely" reason.

It looks like a race on the client-side, between receive [FIN, ACK] and request ~16 microseconds, and possibly, the "close" message was in mailbox of httpc connection manager but the request was already sent into connection or smth like...

But, it seems like, cowboy doesn't add the "Connection: close" header to the last successful reply, which could help the connection managed don't route the new requests to the connection which will be closed soon or already closed...

**Comment by essen** [comment]
Cowboy adds Connection: close when it knows it's going to close the connection, not when closing the connection as a result of a timeout, because there's no way to signal that in HTTP/1.1. You should either increase the timeouts or make sure connections don't stay idle too long. This problem does not exist with HTTP/2 due to the GOAWAY frame existing.

**Comment by juise** [comment]
@essen hmm, I'm a little bit confused, could you explain please, why did you talk about timeout? There is no timeout at all in my case

**Comment by essen** [comment]
The first `[FIN, ACK]` line in TCP > Timestamps says `[Time since previous frame in this TCP stream: 5.001000000 seconds]`, pretty sure you just have a 5 seconds timeout somewhere in the Cowboy configuration. Might be a default value, Cowboy defaults used to be very low but they were relaxed a while back.
