### ISSUE TITLE
Cowboy 2.8 failed when sending `set-cokie` header for HTTP2

### ISSUE THREAD

**Issue by tduccuong** [ninenines/cowboy#1483]
Hi,

I am writing a http proxy based on Cowboy 2.8. Upon receiving a request, the proxy makes a new request (built on the client request) to destination site and relays the received response back to client. Now sometimes there is the `set-cookie` header in the response that makes cowboy choking:
```
#PID<0.2307.0> exit with reason: {:function_clause, [{:cowboy_http2, :"-headers_to_list/1-lc$^0/1-0-", ["device_env=4; Expires=Thu, 12 Nov 2020 17:20:10; Domain=.example.com; Path=/"], [file: '/path/to/deps/cowboy/src/cowboy_http2.erl', line: 761]}, {:cowboy_http2, :headers_to_list, 1, [file: '/path/to/deps/cowboy/src/cowboy_http2.erl', line: 761]}, {:cowboy_http2, :send_headers, 5, [file: '/path/to/deps/cowboy/src/cowboy_http2.erl', line: 754]}, {:cowboy_http2, :send_response, 5, [file: '/path/to/deps/cowboy/src/cowboy_http2.erl', line: 745]}, {:cowboy_http2, :commands, 3, [file: '/path/to/deps/cowboy/src/cowboy_http2.erl', line: 622]}, {:cowboy_http2, :loop, 2, [file: '/path/to/deps/cowboy/src/cowboy_http2.erl', line: 247]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
```

In the above error, the header was: 
```
set-cookie: device_env=4; Expires=Thu, 12 Nov 2020 17:20:10; Domain=.example.com; Path=/
```

Actually, the key originally was `Set-Cookie`, but cowboy does not seem to like it, so I lowercase it to `set-cookie`. 

Any idea is very welcome!
Thanks a lot!

**Comment by essen** [comment]
You need to call the `cowboy_req:set_resp_cookie` functions for this header. The set-cookie header must be handled specially because it breaks the normal HTTP parsing rules.

**Comment by tduccuong** [comment]
When I use `cowboy_req:set_resp_cookie`, i got this error: 
```
11:27:22.228 [error] Ranch protocol #PID<0.2313.0> of listener :http_proxy (connection #PID<0.2310.0>, stream id 1) terminated
** (exit) {:badmatch, {34, 1}}
```

**Comment by essen** [comment]
I've never seen an error looking like this.

**Comment by tduccuong** [comment]
well, but it happening to me now...

it definitely a mishandling of the cookie value I think. The value is: 
```
device_env=4; Expires=Thu, 12 Nov 2020 17:20:10; Domain=.example.com; Path=/
```

Looking at `cowboy_req.erl` I see this comment:
```
%% The cookie value cannot contain any of the following characters:
%%   ,; \t\r\n\013\014
```

So clearly the cookie value violates that at least with character `;`. Not sure anything else. I will do some experiment to see.

**Comment by essen** [comment]
I mean you can't give the unparsed set-cookie header. If you want to give the unparsed header you can modify Req directly by setting `resp_cookies`.

**Comment by tduccuong** [comment]
thanks, I got it working. Just for anyone else who may comes across this issue. Here is what I did (I am using Elixir but the code can easily be translated to Erlang):
```
cookie_str = Map.get(response_headers, "set-cookie")
Map.put(req, :resp_cookie, %{"set-cookie" => <raw-set-cookie-string>})
```

**Comment by ShedPlant** [comment]
I also have an HTTP proxy app using cowboy and ran into this same problem when my behind-proxy-server returned `set-cookie` header.

I don't really understand why this issue was closed instead of fixing cowboy to 'just work' 😕 ?

Anyway thanks @tduccuong for sharing your workaround. My workaround (but this snippet is not full working code) looks like:

```erlang
  {ok, Status, HeaderMap, RespBody} = my_custom_functionality:http_forward(ForwardHost, Req, AdditionalHeaders),
  CookieHeaderSet = maps:is_key(<<"set-cookie">>, HeaderMap),
  if
    CookieHeaderSet == true ->
      %% https://github.com/ninenines/cowboy/issues/1483
      SetCookieHeader = maps:get(<<"set-cookie">>, HeaderMap),
      HeaderMapWithoutSetCookie = maps:remove(<<"set-cookie">>, HeaderMap),
      ReqWithSetCookieWorkaround = maps:put(resp_cookies, #{<<"set-cookie">> => SetCookieHeader}, Req),
      ReplyToClient = cowboy_req:reply(Status, HeaderMap, RespBody, ReqWithSetCookieWorkaround);
    true ->
        ReplyToClient = cowboy_req:reply(Status, HeaderMap, RespBody, Req)
  end,
```

**Comment by essen** [comment]
> I don't really understand why this issue was closed instead of fixing cowboy to 'just work' 😕 ?

Because it's not possible. Cowboy uses a map for headers, because normally headers can be concatenated if there's more than one with the same name. Except for set-cookie, which has to be handled specially because we can't do this concatenation.

Your "fix" would only work in the cases where you're trying to send a single set-cookie in the response, and not in the cases where you need to send multiples. Or the header would be the only one where providing what looks like an iolist actually means something different compared to all the other headers. So it would just add to the confusion. Cowboy can't automatically figure out your intent.

I guess a variant of set_resp_cookie that accepts a raw value would help but I'm not sure it's worth it. Having Cowboy reject responses that contain set-cookie headers would probably be less confusing though.

**Comment by essen** [comment]
I've opened https://github.com/ninenines/cowboy/issues/1619 as a followup. Advice welcome on what would be the most convenient if a function is to be introduced.
