### ISSUE TITLE
Nginx-like 444 support for closing connection without finishing the HTTP response

### ISSUE THREAD

**Issue by dogweather** [ninenines/cowboy#1498]
It'd be great for security to respond in this way to script attacks. Nginx supports the non-standard 444 which it doesn't return to the client; it just logs it and closes the connection, firewall-style.

**Comment by essen** [comment]
You can already send `<<"444">>` instead of an integer. Or `<<"444 Some text">>` if you'd like. Integer status codes are just the standard ones.

**Comment by dogweather** [comment]
@essen And then Cowboy drops the HTTP connection without fully completing it? That's the key part of my question.

> Nginx ... just drops the requests

http://nginx.org/en/docs/http/request_processing.html

**Comment by essen** [comment]
I thought you meant you were behind nginx and nginx would drop the connection when it sees that status.

Is this only for HTTP/1.1 then? Because behavior like this would make little sense for HTTP/2. For HTTP/1.1 Cowboy will drop the connection if it's not worth keeping it alive (too large or undefined size incoming body). You may also set the connection:close header I believe.
