### ISSUE TITLE
Cowboy to production and live update

### ISSUE THREAD

**Issue by GeorgiouJohn** [ninenines/cowboy#1558]
Hi, 
I need to push my system to production so my first thought is to put "make run" as a service when the machine boots. 
I don't know if that sound good. It is my first erlang-cowboy project that goes on production.
Then I need to make updates while the system runs. 
Is there a guide for this? 
Thanks for your time.

**Comment by essen** [comment]
`make run` is for development. For production, `relx` provides a script to start the VM with various modes (foreground for example). From there it depends on where you deploy to. There are probably some guides around this for systemd or other but none that I can personally recommend, because I have not done that in a long time and RabbitMQ which I work on now does not use releases and has its own start script.
