### ISSUE TITLE
Support for websocket subprotocol field

### ISSUE THREAD

**Issue by oribrost** [ninenines/cowboy#193]
Currently cowboy does not allow us to control the sec-websocket-protocol field in the upgrade response. This is needed for proper upgrade negotiation with some browsers (Safari 5.1.5 for example).

**Comment by eproxus** [comment]
Not sure if this is the right place (let me know if not, and I'll create a new issue) but we recently discovered two things:

1. Recent versions of Chrome (not sure which exactly, just tried latest) requires the response header `sec-websocket-protocol` to be set to the same value as the request, otherwise the web socket silently fails to open. Should this behavior be the default in Cowboy? It's kind of weird that a web socket opened with Chrome doesn't work out of the box with Cowboy. (It's also really hard to figure out that this is the problem from web searches)
2. The [subprotocol example](https://ninenines.eu/docs/en/cowboy/2.9/guide/ws_handlers/#_subprotocol) in the Cowboy documentation doesn't work. Calling `cowboy_req:parse_header(<<"sec-websocket-protocol">>, Req0)` returns a list of binaries, and not a tuple list, so calling `lists:keymember/3` on it won't work.

**Comment by essen** [comment]
Please open a ticket for 2. About 1, yes it's normal to close, and no Cowboy should not just echo back this value. For example if the client was requesting MQTT over Websocket and you echo back the value but then don't use the MQTT protocol, it's not going to work very well.
