### ISSUE TITLE
Support Range: in cowboy_rest

### ISSUE THREAD

**Issue by dvv** [ninenines/cowboy#306]
Hi!

Is the subj planned?

TIA,
--Vladimir

**Comment by s-kostyaev** [comment]
You can see partial implementation in https://github.com/ninenines/cowboy/pull/1059. For full imlementation multipart/byteranges reply need to be implemented in cowboy.

**Comment by essen** [comment]
I've started work on full support for RFC7233. Here are the current plans:

* A new callback `ranges_provided/2` to be called after `charsets_provided/2`. It returns a list of range units and their associated callbacks. When a range request is to be served, the callback returned here will be called instead of the one in `content_types_provided/2`.
* The accept-ranges header is built based on the output of `ranges_provided/2` and it's added to the `vary` list. The header will only be sent for resources exporting the callback.
* At the end of the conditional checks (if-match and friends), and if both range and if-range headers are present, then if-range header is checked. If it evaluates to false, a full response will be sent, otherwise a ranged response might be sent.
* After if-range, the range header is parsed, if it fails to parse, a 416 response is sent.
* The range header is then checked against the `ranges_provided/2` and if the unit is unknown, a full response will be sent, otherwise a ranged response might be sent.
* If all other preconditions are valid, the function `range_satisfiable/2` is called. This allows rejecting a range request with a 416 as a last resort, for example if it requests a byte range that's larger than available.
* If all preconditions are valid, the callback defined in `ranges_provided/2` is called instead of the one in `content_types_provided/2` when the time comes to send the body. When it returns, it sends a 206 immediately instead of potentially calling `multiple_choices/2`.

In addition, because RFC7233 defines `multipart/byteranges` and it'd be good to apply it automatically to existing REST handlers, `ranges_provided/2` will accept the tuple `{<<"bytes">>, auto}` to indicate that `cowboy_rest` should take care of splitting the partial content on its own. In that case `cowboy_rest` will call the callback defined in `content_types_provided/2` and will do the splitting itself and building the correct 206 response (with/without multipart as needed) automatically.

This last part will probably require me to implement https://github.com/ninenines/cowboy/issues/984 and https://github.com/ninenines/cowboy/issues/1113 at the same time.

Thoughts?

**Comment by essen** [comment]
I've just pushed 29043aa which contains a full RFC7233 implementation for `cowboy_rest`. I will also add the "auto" mode for byte ranges to simplify adding range support to resources and then I'll also add that to cowboy_static (which uses sendfile and therefore there will be no real performance impact).

**Comment by essen** [comment]
I've pushed three more commits:

* Add the "auto" mode for bytes units that can be enabled via `ranges_provided/2`
* Fix case where a resource responds to a multiple range request using `sendfile` tuples
* Enable range request support in `cowboy_static`

Other than documentation, which will be done once I've confirmed that this fits a customer use case, I believe everything has been added. Please experiment and open new tickets if you find any issues. Thanks!
