### ISSUE TITLE
Option to disable "server" header

### ISSUE THREAD

**Issue by zyro** [ninenines/cowboy#680]
I've seen the discussion on issue #349 but I'm hoping to add to the argument for this feature. Specific versions in the server header are not an issue here, but is there any benefit in disclosing the server type at all?

Page 141 of [RFC 2068](http://www.ietf.org/rfc/rfc2068.txt) specifies the header should be configurable, which can easily be interpreted as allowing the possibility of disabling as well. Some web frameworks I've used recently such as [Dropwizard](http://www.dropwizard.io/) disable this header by default.

In my specific case I'm building a public-facing service and (for now) I want to avoid broadcasting information about my server stack or implementation details, which might then lead to reasonable guesses as to what else might be running.

I'm currently using a `onresponse` hook to drop the header before the response is sent, but it would be nice to have built-in support for this.

**Comment by alexnauda** [comment]
I want to +1 and bump this stale issue. From a security perspective, disclosing implementation details is a huge liability. We all know about Cowboy now; we love it and are adopting it. I propose adding a feature to hide or customize the Server response header in order to allow us to harden Cowboy on the security front and allow us to hide implementation details from concerted and well-funded attackers.

To put this another way, my customers are pen testing me and asking me to hide implementation details. I'd love to use Cowboy but may be forced to replace it if it can't provide this security feature.

**Comment by essen** [comment]
The server header does nothing for security. Attackers don't look at the software and decide what attack to use, they launch all attacks at once automatically and see what sticks. Besides, look at the number of companies advertising their stack openly, do you think that's a security risk too? There's plenty of security considerations to take before removing a header that's only useful for stats.

That said, it's always been very easy to remove the server header if you don't want it. The onresponse hook in 1.x, or a stream handler in 2.x. There's no need to add an option.

**Comment by yordis** [comment]
@essen I may agree with you up to some point but, it is much easier to write bots that look for `server` header and check which one they are using, than try to watch videos and article based on the company for figure out what they are using in their stack.

In fact,

As an attacker, the first thing I will do is to send your random keys to your JSON endpoint and see if you are converting those keys to atoms without any secure system in place, `wink+smile face`

If you are not, I am pretty much sure that hitting your atoms limited on your VM will happens really quick.

This is just me sitting on my computer watching my bot how it finds `cowboy` based servers and exploit them if they do not do anything about the described issue.

I would say,

Opinions are just opinions, but when it comes to security, don't make it easier and do not assume anything please, that is the first insecure step.

For those who may no care about this, could always enable it,

but for those who don't know about the implications, let's help them out by disabling this by default.

**Comment by essen** [comment]
As an attacker I would just run nmap, metasploit and others on your public-facing servers. If I am not targeting anyone in particular and nothing was found (ie I just want a server for a botnet or something) then I move on to the next IP.

If I am targeting you in particular and that fails, I would first search for what your stack is. Turns out many companies advertise them in blog posts and other. See also https://stackshare.io/

Alternatively I would try social engineering, that's easier in many cases.

Anyway you can already remove it if you don't want it so what's the problem? In Cowboy 2 that's done using a stream handler.

**Comment by yordis** [comment]
@essen I am not arguing at all that you could figure out my stack by doing the stuff you describe, we both agree on that.

But,

it is not same do social engineering and checking stackshare.io website vs just running a scrawling bot that try to find server out there that run cowboy and `hopefully` they didn't do what I described.

> Anyway you can already remove it if you don't want it so what's the problem? In Cowboy 2 that's done using a stream handler.

The issue is that I can't remove the header but being by default on cowboy.

Security should be enabled by default. I gave you a simple example of what people could be doing out there, hopefully they know what I mean by creating atoms dynamically by me passing random parameters (Elixir Phoenix uses string based maps so this is not an issue there at atleast)

That is just one in many,

And people could exploit a lot of these use cases by just knowing if you are running `cowboy`.

**Comment by essen** [comment]
This is a programmer point of view, not an attacker point of view. For an attacker it is just easier and more efficient (in the sense that you'll catch more issues) to run all attacks and see what sticks. The idea that because you rename Cowboy to Apache attackers won't find issues specific to Cowboy is ridiculous.

Your example is not even a good one. Atoms, really? How do you even know that this is what made the node go down as an attacker? You don't. It's indistinguishable from any other DoS. So just DoS everything if that's your goal.

That's why it's not possible by default to remove "Apache" or "Nginx" from the server header either, you have to edit the source or use separate modules. By default you can only remove the version and other tokens. Cowboy has the same approach except it defaults to only ever saying "Cowboy".

Now if it was sending the Cowboy version, Erlang version and other, sure, that would be too much information because it would show you don't maintain your stack. But it doesn't do that. It doesn't send any information that would change the behavior of an attacker. It's secure by default.

Cheers.

**Comment by ffimnsr** [comment]
I beg to disagree to this argument, here is a sample case scenario when a 0-day attack when one finds a vulnerability to a specific server and has yet no bug fixes. The server fingerprint can be utilized to speed up searches on which node server is vulnerable. And also an attacker can use the fingerprint to search vulnerability databases, useful for if the attacker is targeting a specific company / organization site. Here's the thing I found on how to disable it https://arjanvandergaag.nl/blog/cowboy-server-signature.html

**Comment by essen** [comment]
You did not give your sample case scenario.

**Comment by chulkilee** [comment]
See https://github.com/OWASP/wstg/blob/master/document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.2_Fingerprint_Web_Server_OTG-INFO-002.md

> While exposed server information is not necessarily in itself a vulnerability, it is information that can assist attackers in exploiting other vulnerabilities that may exist. Exposed server information can also lead attackers to find version-specific server vulnerabilities that can be used to exploit unpatched servers. For this reason it is recommended that some precautions be taken. These actions include:
> ...

**Comment by essen** [comment]
Yes that's why it only says "Cowboy" and does not include a version number or other components.

**Comment by doublej74** [comment]
+1 for this option

**Comment by luixal** [comment]
My company just dropped EMQX as it MQTT broker (it uses cowboy to handle websocket connections) because of this security issue.

**Comment by essen** [comment]
If true that's hilarious not just because of the overreaction but also because you already can override the header.

It'd be double hilarious if your company dropped EMQX in favor of RabbitMQ.

**Comment by luixal** [comment]
Is there any doc about how to override the header?

Hilarious or not, the company thst audits us sees this things as security concerns and will force us to drop emqx if can't avoid that.

**Comment by essen** [comment]
You need to tell EMQX to see if they want to do something about it. Based on their recent work I'm sure they would either hide it or add an option. In current Cowboy this is done via a stream handler https://ninenines.eu/docs/en/cowboy/2.16/manual/cowboy_stream/

Alternatively put nginx or other in front and configure it like you prefer.

**Comment by luixal** [comment]
> also because you already can override the header.

Actually, this is truly hilarious after you're last response xD

PS: your replies in this issue are kind of disgusting.

**Comment by essen** [comment]
Yes Cowboy users can override the header easily. This is a Cowboy ticket, answers are about Cowboy. In your case you can modify EMQX to drop the header or tell EMQX developers about it. Sorry for trying to be helpful.
