### ISSUE TITLE
cowboy_req:cookie crashes on cookies without values

### ISSUE THREAD

**Issue by bharendt** [ninenines/cowboy#698]
When **headers are not parsed yet**, the `{error, badarg}` returned by `parse_header(<<"cookie">>, Req)` causes a **badmatch** in **current version** of [cowboy_req:420](https://github.com/extend/cowboy/blob/master/src/cowboy_req.erl#L420). See:

```
=ERROR REPORT==== ...
Ranch listener websocket had connection process started with cowboy_protocol:start_link/4 at <0.1584.0> exit with reason: 
{[{reason,{case_clause,{error,badarg}}},...,
{stacktrace,[{cowboy_req,cookie,3,[{file,"src/cowboy_req.erl"},{line,420}]},...
```

This happens when parsing invalid cookies, e.g. **without a value**.

For example when parsing `Cookie: foo=bar; baz; bar=foo`, the **baz** causes `parse_header` function to return `{error, badarg}`.

This return value is only handled, when the **request headers were parsed already**.

According to [rfc6265](http://tools.ietf.org/html/rfc6265#section-4.2.1), it is required to use key-value pairs in cookie headers,

```
 cookie-header = "Cookie:" OWS cookie-string OWS
 cookie-string = cookie-pair *( ";" SP cookie-pair )
```

but apparently some **tracking / metics services** add some plain cookie-name keys **without a value**. I think the value is then considered to be _"true"_. 

Maybe it makes sense to parse also this cookies and return `<<"true">>` as values.

The line was **removed** in this commit: faf64524c6758ae1e27404d2ae1383a23538c538.

**Comment by IgorKarymov** [comment]
Hi @essen . Here is my case (actually very similar to @bharendt ):
I have a big proprietary application that a few years ago used to use such empty cookies for something like application state tracking. Nowadays all this code deprecated (and nobody actually has idea about all the possible names of such cookies). I just deployed some new cowboy based code to production. And I faced with 
next issues:
* because such cookie was set with very long expiration time some users have them in place.
* I can't serve any request to such users because my application using cookie based authorization, and I have to check cookie value for each request.

So what we have here:
* it's possible to set such incorrect value in modern browsers
* modern browsers will send that value to server
* cowboy became totally unusable if such things happen.
* All other web servers in our project have no such issues (TomCat, Netty etc).

**Comment by essen** [comment]
Totally unusable is a bit strong, writing a stream handler to clean the cookie should be trivial in 2.0. I'd say check https://tools.ietf.org/html/rfc6265 and see if they say something about that and then we can discuss.

**Comment by IgorKarymov** [comment]
According to RFC such cookie incorrect for sure:
```abnf
cookie-string = cookie-pair *( ";" SP cookie-pair )
cookie-pair   = cookie-name "=" cookie-value
```
But here we talking not about the standart but about real life.
Not sure about cowboy 2.0 but in 1.x you will have to write your own cow_cookie like parser or hack existing one. Not something that you expecting when working with production ready webserver.

I respect your idea about not hiding errors, but at the same time, it does not make too much sense to throw away all cookies array only because one bad value was passed. So if you interested here is my proposal for future cowboy versions (i believe that I will have to hack existing version anyway):
Let's make it possible to store in cookie list value something like {error, <<"raw error value">>, error_desription()} instead of throwing exceptions. And provide some wrappers access functions for cookie manipulations. If you will try to access such cookie value by the name with wrapper you will get exception, but at the same time, it should be possible to retrieve the raw value with special functions, and do everything what you want with it.

**Comment by essen** [comment]
The RFC is more than these two lines. It should say what the behavior should be when receiving invalid input.
