### ISSUE TITLE
POST and resource_exists

### ISSUE THREAD

**Issue by nevar** [ninenines/cowboy#723]
/books resource exist and I can make GET to it.
When I make POST to /books for create new entry and return {true, "/books/1"}, cowboy return 303 and not 201. So I need define resource_exists callback and make it return false for POST request. This is not very comfortable.
I think we need remove depend on resource_exists callback for POST request (as it can create another resource).
May be `{new, URL}` for 201 and `{true, URL}` for 303? or return to first suggestion in #424?

**Comment by essen** [comment]
I am currently running into this myself and better understand the issue. Indeed, it is confusing, and wrong. Cowboy confuses the resource identified by the request and the resource that ultimately is operated on, which may be different for a POST request.

POST is complicated. POST behavior is defined by the resource, so anything is basically possible. There are two main paths identified by the RFC, 201 and 303. But in reality POST could return anything.

Cowboy limits itself to handling the 201 and 303 cases (+ the cases where POST has the same behavior as PUT). Right now it will return one or the other for the wrong reasons, Ie it checks if the resource targeted by the POST request exists, instead of the one(s) the POST will operate on (potentially creating a new resource).

There are two obvious solutions: a function that says whether the post creates a new resource, and different return values. A function is not very good: if it is called before the operation is done, we don't know yet if a resource will be created. If called after, the developer needs to keep state around to indicate it was created. Might as well just use return values.

Which brings us to what the return values should be.

Currently we have `true | false | {true, ResURL}`, with true taking two different paths depending on whether the resource exists, and the tuple form being POST-specific.

I think instead of a "true" tuple we should use more descriptive names. Maybe something like `{created, URI}` and `{see_other, URI}`.

I think if we go this route, then I can include this as part of Cowboy 1.1.0 (keeping the "true" tuple, marking it as deprecated).

**Comment by christopheradams** [comment]
> I think instead of a "true" tuple we should use more descriptive names. Maybe something like `{created, URI}` and `{see_other, URI}`.

I think this is exactly the right approach. It simplifies the decision chain as well, since it would no longer have to double-check the `exists` state. It would also remove what I think is the main rationale for having `allow_missing_post` default to true.

I would also add that in addition to `{created, URI}` and `{see_other, URI}`, the callback should be able to return `accepted` in order to get a "202 ACCEPTED" response.

**Comment by christopheradams** [comment]
@essen I can try to work up some commits if you would agree on the changes needed.

Backwards-compatible changes:

1. Add any missing tests for `process_content_type/3`, for any desired
   combination of `method`, `exists`, return values, and "location" header.
2. Implement, test, and document new return values:
   - `accepted`
   - `created`
   - `{created, URI}`
   - `{see_other, URI}`
3. Optionally document any return values that should be deprecated.

Backwards-incompatible changes:

1. Drop (or fix inconsistencies in) the `{true, URI}` return value.

What do you think?

**Comment by essen** [comment]
REST currently has next to no tests. I was planning to fix this by writing an rfc7231_SUITE module, testing the semantics of HTTP, since cowboy_rest basically implements that. I don't think it's worth to spend too much time on this until we have such a test suite.

**Comment by christopheradams** [comment]
Ok, good to know!

**Comment by mbj4668** [comment]
I am running into this as well.  What is the status of this issue?

**Comment by essen** [comment]
No progress on the issue, on the other hand there is now a `rest_handler_SUITE` where a test for this would fit. I would suggest someone write a test showing exactly what we want and then go from there.

**Comment by mbj4668** [comment]
Ok, I'll have a look.

**Comment by mbj4668** [comment]
I created PR #1464.

**Comment by essen** [comment]
Merged, closing, thanks!
