### ISSUE TITLE
POST, resource_exists -> false should return 404

### ISSUE THREAD

**Issue by thezerobit** [ninenines/cowboy#756]
POST is only defined for existing target resources, so returning false from resource_exists should return a 404 immediately.

**Comment by sugus-seu** [comment]
How do I make allow_missing_post false?
My Code doesn't work:
allow_missing_post(Req, State, 404) ->
            {false, Req, State}.

**Comment by essen** [comment]
Not sure why you put a 3rd argument there. There's only allow_missing_post/2.

**Comment by christopheradams** [comment]
Apologies in advance for digging up this old thread. I guess the entire issue/discussion could have been avoided if the default for `allow_missing_post` were `false` like it is in Webmachine. What's the rationale for making it `true`?

**Comment by christopheradams** [comment]
Just be more clear, I think you're right about POST, I'm only interested in the assertion "it makes things easier for most people AFAIK". Is there something I can read that says more about this?

Is it the more common scenario for action-oriented resources like, let's say, `sessions/new` that have no representation (so 404 for GET) but can be used to create new resources?

**Comment by essen** [comment]
It's been a long time and the change was made in the very first cowboy_rest commit. I can't answer with precision easily right now.

I do not think `sessions/new` was taken into account, because this is not a very good practice. You'd just go against `sessions` and probably want `false` in that case.

I am OK with debating this further and possibly changing the default in Cowboy 2.0, but it will have to be based on what the RFC says, and it will have to be in a new ticket.

**Comment by christopheradams** [comment]
> I do not think `sessions/new` was taken into account, because this is not a very good practice.

I agree, it's a bad example, for the reason you mention. Maybe better to imagine that `GET /sessions` returns 404 but `POST` creates a new one? Or that `POST /users/123`, if that resource does not exist, can either treat this like `PUT` and return 201 or create a new resource at another URL and return 303?

These are scenarios where `allow_missing_post` is essential, but they seem less common than POSTing to the wrong resource and expecting a 404, like the OP probably did.

For what it's worth, Webmachine and webmachine-ruby default this decision to false. So does Airship. Liberator defaults to true. But what would the RFC say?

**Comment by essen** [comment]
Sure but Webmachine was based on the original HTTP RFC, and contains errors that were fixed by clarifications or additions in the more recent RFC (7230+). Current cowboy_rest still has at least some of them (like wrong handling of if-* headers when both kinds -date and etag- are provided) but I hope to fix them once I thoroughly reviews and test against the RFC.

I do not know if this change is good because it predates those new RFCs. I also do not remember the exact reasoning.

Ultimately, Webmachine and derivatives implement a state machine based on the HTTP semantics, and so the RFC is always right. I don't know if allow_missing_post true is right, we need to look into the RFC to find out, and possibly write down all possible (good) cases to make a decision.

**Comment by christopheradams** [comment]
I don't think it's a question of right or wrong here (per the RFC). Instead, it concerns an assumption that the software makes about what the programmer intends. For example, if you create a route and resource module in cowboy_rest, the software assumes `resource_exists == true` unless you tell it otherwise. That's a pretty fair assumption.

So, what is the assumption when POSTing to a non-existent resource? That's a bit harder to say. But we know the OP had a different assumption in this case than the software. So either the defaults or the docs could be improved here. Anyway, this belongs in a new ticket.
