### ISSUE TITLE
HTTP 202 - Accepted for GET and POST

### ISSUE THREAD

**Issue by jbothma** [ninenines/cowboy#757]
I have a case where a POST can start creating a resource, and give a URL for where it's going to exist, but the client shouldn't expect it to be complete yet. I believe the right response code is 202.

GETs to the resource can provide an indication of the progress of making the resource but shouldn't give response code 200 until it's actually complete, at which point the body will represent the final resource. I believe 202 is also the right response code here.

From http://restpatterns.org/HTTP_Status_Codes/202_-_Accepted it sounds like it's not necessarily the actual resource location that gives the progress info, but if GET can respond with 202, I don't think there's anything wrong with that (the progress info fits into my data model anyway).

Is this something cowboy's REST handler could be made to support? Why is the `delete_complete` callback so specific?

For GET and POST (and HEAD, I guess) I'd propose an `is_complete` callback.

JD

**Comment by christopheradams** [comment]
For "POST 202 Accepted" possible solution mentioned in #757

While the RFC does not appear to specify which methods can result in 202, since it means "the request has been accepted for processing", it does not seem appropriate for GET.

The REST cookbook recommends if you POST and receive 202, a subsequent GET can return:

* Still processing: 200 with status
* On successful completion:  303 to redirect
* On task failure: 200 with error message

**Comment by essen** [comment]
There's only wording about 202 for DELETE, which we handle. There's no wording for other methods so it's up to you. I would recommend continuing to use `cowboy_req:reply/2` along with a stop tuple when you need a 202 for non-DELETE methods. Let's keep `cowboy_rest` close to the standards.

Closing, thanks!
