### ISSUE TITLE
utf8 in body not showing as expected

### ISSUE THREAD

**Issue by pdincau** [ninenines/cowboy#891]
I am retrieving post body using:

    content_types_accepted(Req, State) ->
        {[{<<"application/json; charset=utf-8">>, handle_post}], Req, State}.

and in handle_post/2 I have:

    {ok, ReqBody, Req1} = cowboy_req:body(Req)

but if I have in my request body something as "malé" the payload is not recovered correctly.

Is this something I should specifiy somewhere on cowboy?

**Comment by essen** [comment]
Cowboy returns the bytes that were sent. If you run into issues it's either that they were incorrectly sent, or that you are using the payload incorrectly. You may need to convert to string using the unicode module if that's what you're doing, since UTF-8 code points can be encoded over 1 to 4 bytes (and characters over multiple code points).

**Comment by pdincau** [comment]
Thanks for your support @essen I will definitely take a look at the unicode module.
