### ISSUE TITLE
What is the best way to implement some cache in cowboy server?

### ISSUE THREAD

**Issue by vesperusiak** [ninenines/cowboy#895]
I have a problem that i need to keep some data(per connection) between requests(not in cookies) and as i see cowboy doesn't provide any way to do this directly using library, what is the best way to do this?

My idea is to keep ets with state per conn, where key is pid of cowboy process handling connection, my assumption is that cowboy process is persisting between requests (and that will not change in future releases), is this the best way? or there are better?

**Comment by essen** [comment]
Processes persisting between requests will change in Cowboy 2. *However* there will still be a process valid for the whole connection and you will be able to hook into it.

Do note that when the connection is gone, this state of yours is going to be gone as well. If that's fine for you then this sounds like a reasonable solution. Otherwise you need a kind of session mechanism.

**Comment by essen** [comment]
Closing as there is no real issue here and I answered the question. Enjoy!
