### ISSUE TITLE
why cowboy only implement cookie ,but not implement sessioin for web_server

### ISSUE THREAD

**Issue by wuchuguang** [ninenines/cowboy#902]
i want web_server use session to implement account auth .so on github find https://github.com/dvv/stable   https://github.com/chvanikoff/cowboy_session library. 
two library last update in two year.
session is web_server often use it .why cowboy only cookie.not session ,has other way to auth account on cowboy?

**Comment by essen** [comment]
Well cookies are a standard defined by an RFC. Sessions are ad-hoc solutions that may or may not be implemented using cookies. Cowboy focuses on HTTP related standards.

I don't rule out the possibility to make a project later on to do sessions but this is out of scope right now. Also despite not having been updated recently, I think both of these libraries still work with Cowboy stable, don't they?

Closing since this is not going to be implemented in Cowboy.
