### ISSUE TITLE
websocket not working with ranch proxy protocol

### ISSUE THREAD

**Issue by comtihon** [ninenines/cowboy#904]
Related issues https://github.com/heroku/ranch_proxy_protocol/issues/16, https://github.com/ninenines/cowboy/issues/708
I try to get client's real ip address and use ranch_proxy_protocol for it. As I figured out from https://github.com/ninenines/cowboy/issues/708 all I need is to change Transport to `{ok, _} = ranch:start_listener(client_handler, Acceptors, ranch_proxy,
[{port, Port}], cowboy_protocol, [{env, [{dispatch, Dispatch}]}])`
But it is not working for me. I use both master branches for all repos.
I wrote simple websocket handler and try to connect to it using [gun](https://github.com/ninenines/gun) with ranch_proxy_protocol.
As I can see from scanning traffic - cowboy wan't upgrade protocol, as it get upgrade packet, but don't send websocket packets.
I add some logs and noticed, that on ranch step only difference is in \#http_req.socket difference, as ranch_proxy stores proxyinfo in it.
On upgrading to websocket I saw enother difference -> in proper behaviour ranch_acceptor runs accept loop two more times and call cowboy_protocol:start_link. 
Thats all.
 [proper_log](https://www.dropbox.com/s/qxxtyk3d7wvlhpn/proper_log.txt?dl=0)
 [wrong_log](https://www.dropbox.com/s/sir2fllv63iva1h/wrong_log.txt?dl=0)
Need help or example, how to deal with it. Thanks.

**Comment by essen** [comment]
You have more experience with ranch_proxy_protocol than me. :-)

I suggest trying to find where exactly it doesn't send the expected data.

**Comment by ferd** [comment]
Heroku visibly uses it with cowboy and we do manage to make it work. My guess is that the thing won't work given cowboy

We have however taken over the cowboy functionality, because cowboy expects the active messages to match the socket itself: https://github.com/ninenines/cowboy/blob/1.0.x/src/cowboy_websocket.erl#L211-L229

However, the proxy protocol handling requires the proxy handler to hold more state than the interface allows and context is missing. I'm currently pushing to open-source the heroku proxy (hopefully during this week -- a thing I've said for the last 2-3 weeks now) which has an example on how to do this. 

At the core there's a very similar loop, but rather than matching on the `Port` datatype itself, we define:

```erlang
port(_Transport, Port) when is_port(Port) -> Port;
port(Transport, Port) ->
    %% this allows to override the port in messages for cases like
    %% ranch_proxy_protocol, which aims to look like ranch_tcp
    %% transparently while still holding state.
    case erlang:function_exported(Transport, match_port, 1) of
        true -> Transport:match_port(Port);
        false -> Port
    end.
```
which expands the ranch interface with the [`match_port/1`](https://github.com/heroku/ranch_proxy_protocol/blob/master/src/ranch_proxy_protocol.erl#L218-L219) function to know what will be in messages.

Otherwise the wait/receive loop can't work very well for what the proxy protocol needs vs. the state it has to carry.

**Comment by comtihon** [comment]
@essen 
I try to got rid of ranch_proxy just moving parse code to cowboy_protocol, as you suggest in https://github.com/ninenines/cowboy/issues/708
I added one clause to `parse_request/3`:

    parse_request(<<"PROXY ", Data/binary>>,
    State = #state{socket = Socket, transport = Transport, until = Until}, ReqEmpty) ->
    {Proxy, Other} = case binary:split(Data, [<<"\r\n">>]) of
                         [P, O] -> {P, O};
                         [P] -> {P, <<>>}
                       end,
      case parse_proxy_protocol(Proxy) of
        unknown_peer when Other =:= <<>> ->
          {ok, Data} = recv(Socket, Transport, Until),
          parse_request(Data, State, ReqEmpty),
          {ok, State};
        unknown_peer ->
          parse_request(Other, State, ReqEmpty),
          {ok, State};
        not_proxy_protocol ->
          Transport:close(Socket),
          throw(not_proxy_protocol);
        ProxyInfo when Other =:= <<>> ->
          {ok, Data} = recv(Socket, Transport, Until),
          parse_request(Data, State, ReqEmpty);
        ProxyInfo ->
          parse_request(Other, State, ReqEmpty)
     end;

Parse code is:

    parse_proxy_protocol(<<"TCP", Proto:1/binary, _:1/binary, Info/binary>>) ->
      InfoStr = binary_to_list(Info),
      case string:tokens(InfoStr, " \r\n") of
        [SourceAddress, DestAddress, SourcePort, DestPort] ->
          case {parse_inet(Proto), parse_ips([SourceAddress, DestAddress], []),
            parse_ports([SourcePort, DestPort], [])} of
            {ProtoParsed, [SourceInetAddress, DestInetAddress], [SourceInetPort, DestInetPort]} ->
              {ProtoParsed, SourceInetAddress, DestInetAddress, SourceInetPort, DestInetPort};
            _ ->
              malformed_proxy_protocol
          end
      end;
    parse_proxy_protocol(<<"UNKNOWN", _/binary>>) ->
      unknown_peer;
    parse_proxy_protocol(_) ->
      not_proxy_protocol.

    parse_inet(<<"4">>) ->
      ipv4;
    parse_inet(<<"6">>) ->
      ipv6;
    parse_inet(_) ->
      {error, invalid_inet_version}.

    parse_ports([], Retval) ->
      Retval;
    parse_ports([Port | Ports], Retval) ->
      try list_to_integer(Port) of
        IntPort ->
          parse_ports(Ports, Retval ++ [IntPort])
      catch
        error:badarg ->
          {error, invalid_port}
      end.

    parse_ips([], Retval) ->
      Retval;
    parse_ips([Ip | Ips], Retval) ->
      case inet:parse_address(Ip) of
       {ok, ParsedIp} ->
          parse_ips(Ips, Retval ++ [ParsedIp]);
        _ ->
          {error, invalid_address}
      end.

The only think I try to do is to split proxy header and standard header and process them. Code comes to this clause, it also passes and inits my handler, but I got timeout on client. It doesn't behave so, when I pass ordinary header.
How parsing the request could change whole cowboy behaviour?

**Comment by essen** [comment]
In #708 I suggested making a custom protocol (using it instead of cowboy_protocol) and calling cowboy_protocol:parse_request/3 when you need to handle the request. I did not suggest modifying cowboy_protocol.

There's not much I can help you with here. It's been done a few times by various people but it's not something I currently support.

**Comment by essen** [comment]
Closing this in favor of #912.

**Comment by jimdigriz** [comment]
If anyone is curious, I needed proxy protocol support in cowboy2 so rolled up my sleeves:

https://github.com/ninenines/cowboy/compare/master...jimdigriz:proxy

Changes [`ranch_proxy_protocol`](https://github.com/heroku/ranch_proxy_protocol) side are:
https://github.com/heroku/ranch_proxy_protocol/compare/master...jimdigriz:cowboy
