### ISSUE TITLE
REST OPTIONS vary header

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#972]
Currently the vary header isn't sent back on OPTIONS. We probably should, though. Check if there's anything against that and if it makes sense.

**Comment by christopheradams** [comment]
I'm trying to understand what the RFC says about this. The only header field it mentions is the Allow header, all others being undefined.

The Vary header has two purposes:

1. *To inform cache recipients...* about the resource
2. *To inform user agent recipients that this response is subject to content negotiation*

Since per the RFC "Responses to this method are not cacheable", only purpose (2) is relevant.

The question is, does the Vary header's purpose (2) fit the definition of "any header fields that might indicate optional features implemented by the server and applicable to the target resource," as per the RFC?

While the Vary header might loosely "indicate optional features", unlike the Allow header it doesn't actually tell you what the options are (e.g., which languages, content-types, etc., will work with the resource).

Also note that the OPTIONS response is allowed to have a body, and, if it does, "Content negotiation MAY be used to select the appropriate response format." In that situation it would make more sense to send the Vary header, but in that case the variances would describe the OPTIONS body, not the actual target resource.

**Comment by essen** [comment]
Yep I don't think the Vary header is good for this, since it always relates to the current response being returned (for the OPTIONS request).

What I was looking for at the time was things like Allow but for other infos, like content-types provided/accepted. I do not think such a header exists (or perhaps it does in an experimental or informative RFC).

Regardless, the correct way to provide this information is to provide a hypermedia representation (like HTML) that contains links and forms describing the different methods of accessing this resource. For example links pointing to the different media types allowed in GET requests, or forms for the different POST/PUT/DELETE/PATCH allowed. And that, while I have a lot of interest in it and plans to start a project around it, is out of scope of the Cowboy project.

**Comment by essen** [comment]
Closing! Thanks for the discussion.
